#!/bin/bash

bgdir="$HOME/media/pictures/wallpapers"

if test "$1" = "-l"; then
    # just dont touch it
    tree $bgdir # if you have tree installed
    # find $bgdir -type f | sed -n -e "s/${bgdir//\//\\\/}\///p"
    exit
fi

if test "$1" = "-d"; then
    echo "$bgdir"
    exit
fi

# pass in full path
if test -f "$1"; then 
    file="$1"
elif test -f "$bgdir/$1"; then
    file="$bgdir/$1"
else
    file=$(find $bgdir | shuf -n 1)
fi

feh --bg-fill --no-fehbg $file

if [[ " $@ " =~ " -n " ]] && pgrep dunst; then
    notify-send "set wallpaper to $(basename $file)" -i /usr/share/icons/Adwaita/32x32/mimetypes/image-x-generic-symbolic.symbolic.png
fi 
