#!/bin/bash

# specify your background image directory
bgdir="$HOME/media/pictures/background-images"

if test "$1" = "-l"; then
    # just dont touch it
    # tree $bgdir # if you have tree installed
    find $bgdir -type f | sed -n -e "s/${bgdir//\//\\\/}\///p"
    exit
fi

if test "$1" = "-d"; then
    echo "$bgdir"
    exit
fi

# pass in full path
if test -f "$1"; then
    feh --bg-fill --no-fehbg $1
    exit
fi

if test -f "$bgdir/$1"; then
    feh --bg-fill --no-fehbg "$bgdir/$1"
    exit
fi

feh --bg-fill --no-fehbg -zr $bgdir
